from __future__ import annotations

from pathlib import Path

import numpy as np
import soundfile as sf

from tracyy.media.waveform_cache import default_cache

_DEFAULT_WAVEFORM_POINTS = 65536
_RAW_PEAK_BLOCK_FRAMES = 256


def _normalize_playback_channels(data: np.ndarray) -> np.ndarray:
    pcm = np.asarray(data, dtype=np.float32)
    if pcm.ndim == 1:
        pcm = pcm.reshape(-1, 1)
    if pcm.ndim != 2:
        pcm = pcm.reshape(-1, 1)
    if pcm.shape[1] == 1:
        pcm = np.repeat(pcm, 2, axis=1)
    elif pcm.shape[1] > 2:
        pcm = pcm[:, :2]
    return np.ascontiguousarray(pcm, dtype=np.float32)


def _channel_peak_magnitude(block: np.ndarray) -> np.ndarray:
    """Create a cancellation-safe per-frame magnitude.

    Mean-to-mono can erase stereo material when L/R happen to be opposite in
    phase. For a visual waveform we want the strongest channel magnitude.
    """
    data = np.asarray(block)
    if data.size == 0:
        return np.zeros(0, dtype=np.float32)
    if data.ndim == 1:
        magnitude = np.abs(data.astype(np.float32, copy=False))
    else:
        if data.ndim != 2:
            data = data.reshape(data.shape[0], -1)
        values = data.astype(np.float32, copy=False)
        magnitude = np.max(np.abs(values), axis=1)
    return np.ascontiguousarray(magnitude.reshape(-1), dtype=np.float32)


def _append_raw_peak_blocks(
    chunks: list[np.ndarray],
    carry: np.ndarray,
    magnitude: np.ndarray,
    block_frames: int = _RAW_PEAK_BLOCK_FRAMES,
) -> np.ndarray:
    magnitude = np.asarray(magnitude, dtype=np.float32).reshape(-1)
    if magnitude.size == 0:
        return carry
    if carry.size:
        magnitude = np.concatenate((carry, magnitude))

    complete = (magnitude.size // block_frames) * block_frames
    if complete:
        grouped = magnitude[:complete].reshape(-1, block_frames)
        chunks.append(np.max(grouped, axis=1).astype(np.float32, copy=False))
    if complete < magnitude.size:
        return np.ascontiguousarray(magnitude[complete:], dtype=np.float32)
    return np.zeros(0, dtype=np.float32)


def _pool_peaks_to_limit(peaks: np.ndarray, points: int) -> np.ndarray:
    """Peak-pool the whole track into <= points bins with exact time coverage.

    There is deliberately no zero-padding. Every output point corresponds to
    real source material, which prevents an artificial zero/silence tail at the
    right side of the timeline.
    """
    source = np.asarray(peaks, dtype=np.float32).reshape(-1)
    if source.size == 0:
        return np.zeros(2, dtype=np.float32)

    target = max(512, int(points))
    if source.size <= target:
        return np.ascontiguousarray(source, dtype=np.float32)

    starts = np.floor(
        np.arange(target, dtype=np.float64) * (source.size / float(target))
    ).astype(np.int64)
    starts = np.clip(starts, 0, source.size - 1)
    # target < source.size, therefore starts are strictly increasing.
    pooled = np.maximum.reduceat(source, starts)[:target]
    return np.ascontiguousarray(pooled, dtype=np.float32)


def _finalize_full_track_peaks(
    chunks: list[np.ndarray], carry: np.ndarray, points: int
) -> np.ndarray:
    if carry.size:
        chunks.append(np.asarray([float(np.max(carry))], dtype=np.float32))
    if not chunks:
        return np.zeros(2, dtype=np.float32)

    source = np.concatenate(chunks).astype(np.float32, copy=False)
    envelope = _pool_peaks_to_limit(source, points)

    maximum = float(np.max(envelope)) if envelope.size else 0.0
    if maximum > 1.0e-9:
        envelope = envelope / maximum
    # Same visual response as the older Tracyy gray waveform, but the source is
    # now generated by a full-track streaming analyzer rather than full PCM RAM.
    envelope = np.power(np.clip(envelope, 0.0, 1.0), 0.72)
    return np.ascontiguousarray(envelope, dtype=np.float32)


def _analyze_soundfile_full_track(path: str, points: int) -> np.ndarray:
    chunks: list[np.ndarray] = []
    carry = np.zeros(0, dtype=np.float32)

    with sf.SoundFile(path, mode="r") as source:
        while True:
            block = source.read(131072, dtype="float32", always_2d=True)
            if block is None or len(block) == 0:
                break
            magnitude = _channel_peak_magnitude(block)
            carry = _append_raw_peak_blocks(chunks, carry, magnitude)

    return _finalize_full_track_peaks(chunks, carry, points)


def _pyav_frame_to_samples(frame) -> np.ndarray:
    array = np.asarray(frame.to_ndarray())
    if array.size == 0:
        return np.zeros((0, 1), dtype=np.float32)

    # Planar PyAV frames are commonly channels x samples. Packed data can be
    # samples x channels. Pick the orientation using the small channel axis.
    if array.ndim == 2:
        if array.shape[0] <= 32 and array.shape[1] > array.shape[0]:
            array = array.T
    elif array.ndim == 1:
        array = array.reshape(-1, 1)
    else:
        array = array.reshape(array.shape[0], -1)

    values = array.astype(np.float32, copy=False)
    return np.ascontiguousarray(values, dtype=np.float32)


def _analyze_pyav_full_track(path: str, points: int) -> np.ndarray:
    import av

    chunks: list[np.ndarray] = []
    carry = np.zeros(0, dtype=np.float32)
    container = av.open(path)
    try:
        stream = next((item for item in container.streams if item.type == "audio"), None)
        if stream is None:
            raise RuntimeError("File không có audio stream")

        # Decode until EOF. No duration estimate is used to size the waveform;
        # malformed/approximate container duration therefore cannot truncate it.
        for frame in container.decode(stream):
            samples = _pyav_frame_to_samples(frame)
            magnitude = _channel_peak_magnitude(samples)
            carry = _append_raw_peak_blocks(chunks, carry, magnitude)
    finally:
        container.close()

    return _finalize_full_track_peaks(chunks, carry, points)


def analyze_waveform(path: str, points: int = _DEFAULT_WAVEFORM_POINTS) -> np.ndarray:
    """Analyze the complete audio file in a spawned worker process.

    Playback remains streaming. This job independently reads the complete file,
    stores only small peak blocks, and returns a compact full-track envelope.
    """
    normalized = str(Path(path).resolve())
    target_points = max(512, int(points))

    cached = default_cache.load(normalized, target_points)
    if cached is not None:
        return cached

    try:
        preview = _analyze_soundfile_full_track(normalized, target_points)
    except Exception:
        try:
            preview = _analyze_pyav_full_track(normalized, target_points)
        except Exception as exc:
            raise RuntimeError(
                f"Không phân tích được waveform: {Path(normalized).name}\n"
                "Định dạng không được libsndfile hỗ trợ và PyAV không decode được.\n\n"
                f"Chi tiết: {exc}"
            ) from exc

    default_cache.store(normalized, target_points, preview)
    return preview
